/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kongdy_hasee_magicsound_voicehelp_Voicer */

#ifndef _Included_com_kongdy_hasee_magicsound_voicehelp_Voicer
#define _Included_com_kongdy_hasee_magicsound_voicehelp_Voicer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kongdy_hasee_magicsound_voicehelp_Voicer
 * Method:    fix
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_kongdy_hasee_magicsound_voicehelp_Voicer_fix
  (JNIEnv *, jclass, jstring,jint);

#ifdef __cplusplus
}
#endif
#endif
